apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: # these labels are replica set labels, every k8 resource can have labels.
    app: mongodb
    tier: db
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod labels
      app: mongodb
      tier: db
      project: roboshop
  template: # this one is nothing but pod definition.
    metadata:
      labels: #these are the pod labels.
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: dasaridevops/mongodb:1.0.0
      imagePullSecrets:
        - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: mongodb
    tier: db
    project: roboshop
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017 #belongs to service
      targetPort: 27017 #belongs to container
  