apiVersion: v1
kind: Service
metadata:
  name: nodeport-ex
spec:
  selector:
    app: nodeport
  ports:
    - protocol: TCP
      port: 80 #belongs to service
      targetPort: http-web-svc #belongs to container
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    app: nodeport
spec:
  containers:
  - name: nodeport-pod
    image: nginx
    ports:
    - containerPort: 80
